// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXUhKrN86S0ZNwzrzi6xRZ8meBCubdaI',
    appId: '1:725376365522:web:77d2f49bafaa51d8470e0b',
    messagingSenderId: '725376365522',
    projectId: 'recipto-5dc45',
    authDomain: 'recipto-5dc45.firebaseapp.com',
    storageBucket: 'recipto-5dc45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzPiovIep_god2o5SRfTNrvsKie0ybwM8',
    appId: '1:725376365522:android:e5a652b953896c95470e0b',
    messagingSenderId: '725376365522',
    projectId: 'recipto-5dc45',
    storageBucket: 'recipto-5dc45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARenRh8M8oQaxx1D60phi0-oYOVpmW_Uc',
    appId: '1:725376365522:ios:177aa8a06a2704fb470e0b',
    messagingSenderId: '725376365522',
    projectId: 'recipto-5dc45',
    storageBucket: 'recipto-5dc45.firebasestorage.app',
    iosBundleId: 'com.example.recipto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARenRh8M8oQaxx1D60phi0-oYOVpmW_Uc',
    appId: '1:725376365522:ios:177aa8a06a2704fb470e0b',
    messagingSenderId: '725376365522',
    projectId: 'recipto-5dc45',
    storageBucket: 'recipto-5dc45.firebasestorage.app',
    iosBundleId: 'com.example.recipto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfXUhKrN86S0ZNwzrzi6xRZ8meBCubdaI',
    appId: '1:725376365522:web:4c01ea3103eb42a5470e0b',
    messagingSenderId: '725376365522',
    projectId: 'recipto-5dc45',
    authDomain: 'recipto-5dc45.firebaseapp.com',
    storageBucket: 'recipto-5dc45.firebasestorage.app',
  );
}
